ShopBike/Areas/Admin/Controllers/OrderDetailController.cs
using Models.DAO;
using Models.EF;
using ShopPhone.Areas.Admin.Controllers;
using System.Web.Mvc;

namespace ShopBike.Areas.Admin.Controllers
{
    public class OrderDetailController : BaseController
    {
        private OrderDetailDAO dao = new OrderDetailDAO();
        private ProductDAO proDao = new ProductDAO();
        private static int currentId;

        public ActionResult Index(int orderID, int page = 1, int pageSize = 10)
        {
            currentId = orderID;
            ViewBag.OrderId = orderID;
            var model = dao.ListAllPaging(orderID, page, pageSize);
            return View(model);
        }

        public ActionResult Create()
        {
            var selectList = new SelectList(proDao.GetAll(), "ID", "Name", 1);
            ViewData["Products"] = selectList;
            ViewBag.OrderId = currentId;
            return View();
        }

        public ActionResult Edit(int orderID, int productID)
        {
            var Product = dao.GetListODByODIdAndPDId(orderID, productID);
            return View(Product);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(OrderDetail orderDetail)
        {
            orderDetail.OrderID = currentId;
            var id = dao.Create(orderDetail);
            if (id)
            {
                return RedirectToAction("Index", new { orderID = currentId });
            }
            else
            {
                ModelState.AddModelError("", "Add successfully");
            }
            return RedirectToAction("Index", new { orderID = currentId });
        }

        [HttpDelete]
        public ActionResult Delete(int orderId, int productId)
        {
            var item = dao.GetListODByODIdAndPDId(orderId, productId);
            if (dao.Delete(item))
            {
                return RedirectToAction("Index", new { orderID = currentId });
            }
            else
            {
                ModelState.AddModelError("", "Delete successfully");
                return RedirectToAction("Index", new { orderID = currentId });
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(OrderDetail orderDetail)
        {
            if (ModelState.IsValid)
            {
                var result = dao.Update(orderDetail);
                if (result)
                {
                    return RedirectToAction("Index", new { orderID = currentId });
                }
                else
                {
                    ModelState.AddModelError("", "Modify successfully");
                }
            }
            return RedirectToAction("Index", new { orderID = currentId });
        }
    }
}

ShopBike/Areas/Admin/Views/OrderDetail/Create.cshtml
@model Models.EF.OrderDetail

@{ ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml"; }

<div class="right__title">Thêm chi tiết hóa đơn mã: @ViewBag.OrderId</div>
<div class="right__formWrapper">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="right__inputWrapper">
            @Html.LabelFor(model => model.ProductID, "Mã sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", ViewData["Products"] as SelectList, "--Chọn sản phẩm--", new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.OrderID)

        <div class="right__inputWrapper">
            @Html.LabelFor(model => model.Quantity, "Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="right__inputWrapper">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>}
</div>

ShopBike/Areas/Admin/Views/OrderDetail/Edit.cshtml
@model Models.EF.OrderDetail

@{ ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml"; }

<div class="right__title">Sửa chi tiết hóa đơn mã số @Model.OrderID</div>
<div class="right__formWrapper">
    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="right__inputWrapper">
                                    @Html.LabelFor(model => model.ProductID, "Mã sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ProductID, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                                <div class="right__inputWrapper">
                                                    @Html.LabelFor(model => model.OrderID, "Mã đơn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.OrderID, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.OrderID, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>

                                                                <div class="right__inputWrapper">
                                                                    @Html.LabelFor(model => model.Quantity, "Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
                                                                    <div class="col-md-10">
                                                                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                                                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                                                    </div>
                                                                </div>

                                                                                <div class="right__inputWrapper">
                                                                                    <div class="col-md-offset-2 col-md-10">
                                                                                        <input type="submit" value="Lưu" class="btn btn-default" />
                                                                                    </div>
                                                                                </div>}
</div>

ShopBike/Areas/Admin/Views/OrderDetail/Index.cshtml
@model PagedList.IPagedList<Models.EF.OrderDetail>
@using PagedList.Mvc
@{ ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml"; }

<div class="right__title">Chi tiết hóa đơn mã: @ViewBag.OrderId</div>
<div class="right__table">
<a class="btn btn-default" href="/Admin/OrderDetail/Create">Thêm chi tiết sản phẩm</a>
<div>
    <br />
</div>
    <div class="right__tableWrapper">
        <table>
            <thead>
                <tr>
                    <th>Mã đơn</th>
                    <th>Tên sản phẩm</th>
                    <th>Số lượng</th>
                    <th colspan="2"></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
    <tr>
        <td>@item.OrderID</td>
        <td>@item.Product.Name</td>
        <td>@item.Quantity</td>
        <td class="right__iconTable"><a href="@Url.Action("Edit","OrderDetail", new { orderId = item.OrderID, productId = item.ProductID})">Sửa</a></td>
        <td class="right__iconTable">
            @Ajax.ActionLink("Xóa", "Delete", new { orderId = item.OrderID, productId = item.ProductID },
                                                                  new AjaxOptions
                                                                  {
                                                                      Confirm = "Do you want to delete this order detail?",
                                                                      OnComplete = "$(this).closest('tr').remove()",
                                                                      HttpMethod = "Delete"
                                                                  }, new { })
        </td>
    </tr>}
            </tbody>
        </table>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @ViewBag.searchString }), new PagedListRenderOptions
   {
       UlElementClasses = new string[] { "paged_list_ul" },
       LiElementClasses = new string[] { "paged_list_li" },
   })
    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}